# Generated by Django 4.2.1 on 2023-07-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='mypics/')),
                ('product_name', models.CharField(max_length=20, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
