# Generated by Django 4.2.1 on 2023-07-13 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='image_description',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='picture',
            name='image_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
