# Generated by Django 4.2.1 on 2023-07-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_picture_image_description_picture_image_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='mypics/')),
                ('image_name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='picture',
            name='image_description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
