# Generated by Django 4.2.1 on 2023-07-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_image_alter_picture_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='mypics/')),
                ('image_name', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
