# Generated by Django 4.2.1 on 2023-07-13 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='images',
            new_name='image1',
        ),
    ]
