# Generated by Django 4.2.1 on 2023-07-13 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_image1_image_description_alter_image1_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='image1',
            name='image_desc',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
