# Generated by Django 4.2.1 on 2023-07-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_image1_image_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image1',
            name='image_desc',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
