# Generated by Django 4.2.1 on 2023-07-13 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_image1_image_desc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='icon',
            new_name='sm_icon',
        ),
    ]
