# Generated by Django 4.2.1 on 2023-07-13 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_contact_icon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact_icon',
        ),
        migrations.DeleteModel(
            name='sm_icon',
        ),
    ]
